spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/jeraldin
      username: postgres
      password: springcourse
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: vVFdS0WHjfpY56sTwGrKxH+9hs2OihqLyCDj+VHgnfORDPcI+85BBtuBB56tPifs
  lifetime: 600m
